### PR TITLE
Pluswin

### PR DESCRIPTION
**Pull request by Hello71**

### CODE REVIEW

**Comment by splintermind** [comment]
I've merged this in 71fa866 so I have no idea why it's not tracking it.

**Comment by Hello71** [comment]
note that apparently this stuff doesn't actually build. https://travis-ci.org/Hello71/Dwarf-Therapist/jobs/34961286

**Comment by splintermind** [comment]
Should be fixed with the changes in ec78e3c

**Comment by Hello71** [comment]
ping

**Pull request merged**
