### PR TITLE
Miscellaneous build system improvements.

### PR DESCRIPTION
**Pull request by Hello71**

### CODE REVIEW

**Comment by Hello71** [comment]
1. why'd you have to create a new commit instead of using mine
2. that's still not right.  
   2.1. `git rm Makefile`. the whole point of qmake is to make the Makefile; copying it randomly does _not_ work.  
   2.2. "'`NCLUDEPATH`"

**Comment by splintermind** [comment]
Yes I'm aware of the typo. It was a conflicting merge so I made the adjustments manually (hence the typo).

**Comment by Hello71** [comment]
the only thing that "conflicted" was the Makefile, which could have been easily remedied by pulling it into your repo and doing `git rm Makefile`, like so:

```
git pull https://github.com/Hello71/Dwarf-Therapist DF2014
git rm Makefile
git commit
```

**Comment by splintermind** [comment]
Alright, got it. My git-fu is not up to par and I shouldn't have manually merged the changes, regardless of how small. Lesson learned.

**Comment by Hello71** [comment]
it's not a huge issue, but generally people prefer to be attributed -- after all, that's what the git author field is for.

even torvalds does it even though he receives all patches via email: https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/log/

oh, and obviously (as you've seen) even with the smallest changes, mistakes can happen; it's better to let the tools handle that for you instead of doing it manually.

**Comment by splintermind** [comment]
I didn't even consider the attribution aspect, but I wasn't intentionally trying to offend. Once your process_vm can be merged you'll have a nice big attribution.

I usually do rely on the tools, but for 5 lines I figured what the hell.. at any rate I'm exhausted and mistakes were made. Which I've been thoroughly chided for.

**Pull request closed without merging**
