### PR TITLE
Adding checkinstall script for *buntu building

### PR DESCRIPTION
**Pull request by int-ua**

### CODE REVIEW

**Comment by Hello71** [comment]
sketchy. better fix the actual debbuild.

**Comment by int-ua** [comment]
What exactly is sketchy IYO?
Of course it's better to fix debuild. But it will take a lot more time.

**Comment by int-ua** [comment]
bash scripts/make-srctar
debuild -us -uc -b
works on https://github.com/int-ua/Dwarf-Therapist/commit/f15559e4e88190c64ef57e238ebe6d120d098f16
But I don't know yet know what to do with debuild -S. Feel free to fix it yourself.

**Comment by int-ua** [comment]
https://github.com/splintermind/Dwarf-Therapist/pull/206

**Pull request closed without merging**
