### PR TITLE
Speed up compilation and make compatible with qt4 (clean version)

### PR DESCRIPTION
**Pull request by myk002**
This pull request removes inclusions of &lt;QtWidgets&gt; and replaces it with the individual required header files. This is recommended by the QT dev guides to speed up compilation (and it does).

This also has the fortuitous side effect of making the code mostly qt4 compatible. After swapping out the headers, there were only a few places where code differences between qt4 and qt5 needed to be addressed.

This code has been compiled and tested with both qt-4.8.5 and qt-5.3.1.

Fixes:
https://github.com/splintermind/Dwarf-Therapist/issues/115
https://github.com/splintermind/Dwarf-Therapist/issues/60
and probably:
https://github.com/splintermind/Dwarf-Therapist/issues/27

### CODE REVIEW

**Comment by Hello71** [comment]
not sure if checking qt version is the right solution.

**Comment by myk002** [comment]
what would you suggest?  ifdef'ing on the type names?

**Comment by myk002** [comment]
All the examples I saw for qt4-qt5 compatibility used the method I used -- #if on the qt version

**Comment by Hello71** [comment]
well, if you're so worried about compile time, at least make script/qml conditional in the project.

**Comment by Hello71** [comment]
qtconcurrent is Since:  Qt 4.4. otherwise, lgtm.

**Comment by anders-larsson** [comment]
Hi,

I've tested this on a system with both QT 4.8.5 and 5.3.1 (same as you apparently) and it built correctly for me with qt4. The following warning message was shown however when qmake for qt4 was called:
`Project MESSAGE: Warning: unknown QT: qml` (module from new qtconcurrent package)

When attempting to build it with qt5 however it gives the following error which prevents it from creating the Makefile necessary to continue with the build.
`Project ERROR: Unknown module(s) in QT: script`

qtscript was removed as a dependency previously for Dwarf Therapist but perhaps this release requires it again? Or has it been included as a dependency because some faulty logic (for qt5 builds).

**Comment by Hello71** [comment]
2e18f64a5014c99affcbe395bdf72831e6fd73b1

**Comment by anders-larsson** [comment]
Works correctly with the modification!

**Comment by splintermind** [comment]
So is the consensus that this is stable enough to merge, or are we still debating the #if technique used?

**Comment by Hello71** [comment]
> qtconcurrent is Since: Qt 4.4. otherwise, lgtm.

I'm not too happy with the `#if`s everywhere, but I don't think there's a better solution.

**Comment by splintermind** [comment]
Agreed. It may be a pain in the ass to maintain, but I haven't found a better solution either. On the other hand, I'm certain anyone using a distro without QT5 will let us know if something breaks...

**Comment by Hello71** [comment]
or you could use travis and set up a build configuration to do a matrix of debug/release qt4/qt5 builds.

**Comment by Hello71** [comment]
2e0d76c17f3253a8f77c585091bda0bef3193034

**Comment by myk002** [comment]
Thanks, Hello71 -- I pulled in the modification to dwarftherapist.pro, and all warnings are now gone.

**Comment by splintermind** [comment]
I'm going to merge this for now since the compile optimizations are a much needed update. ~~I haven't worked with travis before, so I'll have to read up and see if/how that will work as a replacement for the #if declarations moving forward.~~

**Pull request merged**
