### PR TITLE
Move etc -> share, use applicationDirPath

### PR DESCRIPTION
**Pull request by Hello71**
I haven't actually tested installation, but I'm virtually certain that it'll work fine.

the correct solution here is to have a specified path at compile-time, like with autoconf.

### CODE REVIEW

**Comment by splintermind** [comment]
So is the idea here: 'move/rename every o/s <code>etc</code> to <code>share</code> so it works on linux'?

**Comment by anders-larsson** [comment]
Hi,

I tested the changes for you. It does not work correctly I'm afraid. It builds correctly currently and puts the files in the expected directories. However during runtime it does not find the required files.

```
2014-Aug-15 16:30:50.178 INFO   core    beginning to read settings [src/dwarftherapist.cpp:170] (read_settings)
2014-Aug-15 16:30:50.188 INFO   core    finished reading settings [src/dwarftherapist.cpp:198] (read_settings)
2014-Aug-15 16:30:50.223 INFO   core    attempting connection to running DF game [src/mainwindow.cpp:318] (connect_to_df)
2014-Aug-15 16:30:50.225 ERROR  core    No valid memory layouts found in the following directories... () [src/dfinstance.cpp:125] (DFInstance)
2014-Aug-15 16:30:50.284 WARNING    core    can't find running copy [src/dfinstancelinux.cpp:314] (find_running_copy)
```

From strace:

```
16486 openat(AT_FDCWD, "/usr/bin/../share/memory_layouts/linux", O_RDONLY|O_NONBLOCK|O_LARGEFILE|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

**Comment by Cerbsen** [comment]
build and install work on Debian and Arch, but DwarfTherapist won't run, it seems .../share/"dwarftherapist"/... folder is missing

edit
changing every .../share/... to .../share/dwarftherapist/... in your cpp file changes did the trick

nice sideeffect, you solved the "run.log" problem in a way... changing dir to where the logfile should be created before running DwarfTherapist

did some "standalone version" testing, changes did not break LNP capabilities

**Comment by Cerbsen** [comment]
I think this change (in the current state) will break DT for windows and maybe osx as there is no /bin folder to move up from.

Also linux depends on "../share/dwarftherapist/memory_layouts"
where windows depends on "../share/memory_layouts"

**Comment by anders-larsson** [comment]
@Cerbsen: Why not just change them for other operating systems too? Because from my point of view share/ etc/ and other directory names used are Linux specific and for other systems it's just a directory that contains data. Mac OSX and Windows installs applications into as an container (installation directory is a single directory with sub directories) while Linux installs it into separate locations (/etc, /usr and so on).

My point is that the windows and Mac OSX files could probably be moved so the path is ../share/dwarftherapist/memory_layouts too. It would look a bit weird though since it would probably be name something similar to this on Windows: C:\Program Files\Dwarf-Therapist\share\dwarftherapist\memory_layouts if I'm not mistaken. I'm not sure how Dwarf-Therapist is packaged for Windows/Mac OSX.

**Comment by Hello71** [comment]
blah blah untested install, but at least I tried running it this time.

can I just use autotools? starting to hate qmake.

**Comment by Hello71** [comment]
wait, no, that won't work as intended.

**Comment by Hello71** [comment]
/me grumbles

is the "default" gridviews supposed to be modified?

**Comment by splintermind** [comment]
Neither the game_data.ini nor the default_gridviews.dtg should be modified manually. default_gridviews.dtg is specifically for mods to package their own custom views (see masterwork) and otherwise shouldn't even be there for vanilla.

**Comment by Cerbsen** [comment]
build and installed... confirm working (connect, read, modify) on Mint 17

**Comment by Hello71** [comment]
great, now I just need to actually install the file. I hate qmake.

**Comment by Cerbsen** [comment]
with these changes dwarftherapist will stop creating log files in every folder started from... tested under linux
... at least as long you make install or run with sudo... doh

'dwarftherapist.pro'
win32
DEFINES += 'LOGFILEPATH=\\"log/run.log\\"'
macx
DEFINES += 'LOGFILEPATH=\\"log/run.log\\"'
unix
DEFINES += 'LOGFILEPATH=\\"/var/log/dwarftherapist/run.log\\"'

unix
log.path = /var/log/dwarftherapist
log.files += dist/run.log
INSTALLS += log

log_mod.path = /var/log/dwarftherapist
log_mod.extra = chmod 766 $(INSTALL_ROOT)/var/log/dwarftherapist/run.log
log_mod.depends = install_log
INSTALLS += log_mod

'dwarftherapist.cpp'
TruncatingFileLogger *log = m_log_mgr->add_logger(LOGFILEPATH);

**Comment by Hello71** [comment]
how many times do I have to elaborate that _user_ _programs_ _must_ _not_ _write_ _to_ _system_ _directories_.

also, I didn't touch the logger code at all. (shiver)

**Comment by wRAR** [comment]
The user should be allowed to install updated memory layouts so they should be searched for in /etc (real /etc, not /usr/share/dwarftherapist/etc), even if bundled ones are shipped in /usr/share.

**Comment by Hello71** [comment]
splinterz, how are the other platform's releases built?

**Pull request merged**
