### PR TITLE
hacky setting of permissions on the shell script

### PR DESCRIPTION
**Pull request by ghost**
I added proper executable permissions on the bash script (in what I'm sure will make people who actually use qmake cringe at how I did it), because running `sh dwarftherapist` is silly when you could just run `dwarftherapist`.

### CODE REVIEW

**Comment by wookietreiber** [comment]
As a software package maintainer I urge you to **never** hardcode `usr/bin`. If you hardcode, it is only overridable by patching the file. Instead, use what one can usually specify with `--bindir` via the `configure` script.

**Comment by ghost** [comment]
Hrm, I was just following the pattern that was already in the qmake configuration file.

Searching around, it looks like qmake has an `INSTALL_PREFIX` option that's configurable via `qmake PREFIX=/path/to/root/dir`, think that's decent enough? I've seen a plethora of software assume that directories exist (or create them) inside of the installation directory.

**Comment by ghost** [comment]
Read a little more about qmake, wrote an implementation for review over at fa9158513b935543731c00dfc8285db05ae7d614 that excepts `qmake PREFIX=/foo/bar`, but only for *nixes.

**Comment by wookietreiber** [comment]
You are proving my point: in fa91585 is `/usr` replaced with a prefix value (at least in some places), here you are reintroducing it. The build _should be strict_ and replace _all_ occurrences of `/usr` with the prefix value.

**Comment by ghost** [comment]
Right, fa9158513b935543731c00dfc8285db05ae7d614 is the test I wrote to try that out in qmake.

Although not closely related to the original commit here, I could add that to this pull request (or close this one and start anew), and start replacing hardcoded values with `PREFIX` in a later PR.

**Comment by splintermind** [comment]
I admittedly don't spend a lot of time on the linux builds, so I'm willing to update anything you guys feel would be an improvement.

**Pull request merged**
